spring:
  application:
    name: springBoot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test1?serverTimezone=UTC
    username: root
    password: root

    tomcat:
      max-idle: 10
      max-wait: 1000
      min-idle: 5
      initial-size: 5

  redis:
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 800
        max-wait: 1000
        max-idle: 300
    timeout: 1000
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true
    encoding: UTF-8
    mode: HTML
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: 8080
  servlet:
    context-path: /springBoot
    session:
      timeout: 30m
  tomcat:
    uri-encoding: UTF-8
